version: "3.3"
services:
  bot:
    build: .
    volumes:
      - .:/iso_bot
    ports:
      - 8141:8141
    image: app:iso_bot
    container_name: iso_bot_container
    command: python main_prod.py
    env_file:
      - .env.prod
    networks:
      - mysql-network

networks:
  mysql-network:
    external:
      name: mysql-network
